POST http://127.0.0.1:5000/api/register
Content-Type: application/json

{
    "name": "example1",
    "email": "example1@gmail",
    "password": "123456"
}

###
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
    "email": "example1@gmail",
    "password": "123456"
}